### PR TITLE
[WIP] Fixes to Table viewer

### PR DESCRIPTION
**Pull request by pllim**
**DO NOT MERGE YET, WORK IN PROGRESS**

Fixes include:
- Minor PEP8 fixes to `MultiDim`
- Fixed `MultiDim` generating multiple thumbnails for the same extension.
- Fixed `MultiDim` not recognizing `BinTableHDU` as a table.

This is for ejeschke/ginga#370

### CODE REVIEW

**Comment by pllim** [comment]
@ejeschke , I got your table viewer to work. I separated my changes into multiple small commits so you can follow them easily, I hope. As of 826bb38, everything seems to work, except I can't figure out how to get `Header` to change back to table header when I switch back to it via `Thumbs`. I'll continue working on this tomorrow.

**Comment by ejeschke** [comment]
Sounds great, I'll check out what you've got here so far.

**Comment by ejeschke** [comment]
> everything seems to work, except I can't figure out how to get Header to change back to table header when I switch back to it via Thumbs

We'd have to take a careful sweep over the plugins to make sure they do sensible things if an `AstroTable` is set in the channel.  For example, it's not clear to me what `Pan` and `Header` should do--maybe be blanked?

**Comment by ejeschke** [comment]
Your version is working for me.

**Comment by pllim** [comment]
@ejeschke , a FITS table extension has its own header, so ideally `Header` would work for that as well. But I still cannot figure out why `Header` is not behaving properly for table (it works fine for both image and primary header extensions). I find that when I select an extension from `Thumb` or `Contents` (thus bringing data already in memory back to focus), the following happens:
- For primary header, `Header.set_header()` is called once. All is good.
- For image extension, `Header.set_header()` is called _twice_ with the same `AstroImage`. A bit weird but it still works.
- For table extension, `Header.set_header()` is called _twice_, once with the correct `AstroTable`, but then overwritten by a second call with `AstroImage`. When this happens, the displayed header is not the header of the table. I cannot figure out where the second call is coming from.

As for the other plugins, `Histogram` is throwing out some error about `channel.viewer.onscreen_message`. So, I agree that we have to indeed look carefully at how the table interacts with all the other plugins.

As for `Pan`, yes, it should be blank, or at least do nothing without emitting error message about `panset_xy`.

**Comment by ejeschke** [comment]
@pllim, under the `focus_cb` method in `Header.py`, change:

``` python
        image = channel.fitsimage.get_image()
```

to

``` python
        image = channel.get_current_image()
```

**Comment by ejeschke** [comment]
> As for the other plugins, Histogram is throwing out some error about channel.viewer.onscreen_message

For now you can change that line to:

``` python
channel.viewers[0].onscreen_message
```

and that should take care of the error.

**Comment by ejeschke** [comment]
Also, under `set_sortable_cb`, probably should make the same change as in `focus_cb`.

**Comment by pllim** [comment]
Thanks, @ejeschke ! Your suggestions seem to do the trick. It is mostly working now but I still want to look at the rest of the plugins before I call this a success.

**Comment by ejeschke** [comment]
I've got some changes I want to make as well.  Can I merge your changes and then we'll go from there?

**Comment by pllim** [comment]
Sure. Feel free to merge now. I'll wait for your changes and open a separate PR later if needed. Thanks for your patience!

**Pull request merged**
